export const GET_BALANCE = 'GET_BALANCE';
export const GET_CAMPAIGNS = 'GET_CAMPAIGNS';

export const REQUEST_POSTS = 'REQUEST_POSTS'
export const RECEIVE_POSTS = 'RECEIVE_POSTS'
export const SELECT_REDDIT = 'SELECT_REDDIT'
export const INVALIDATE_REDDIT = 'INVALIDATE_REDDIT'
